openapi: 3.0.3
info:
  title: User Profile API
  description: Endpoints for managing user learning profiles
  version: 1.0.0

servers:
  - url: /api
    description: Main API server

paths:
  /profile:
    get:
      summary: Get current user's profile
      operationId: getProfile
      tags: [Profile]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '401':
          description: Not authenticated
        '404':
          description: Profile not found (user hasn't completed setup)

    post:
      summary: Create user profile (first-time setup)
      operationId: createProfile
      tags: [Profile]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileCreateRequest'
      responses:
        '201':
          description: Profile created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Validation error
        '401':
          description: Not authenticated
        '409':
          description: Profile already exists

    put:
      summary: Update user profile
      operationId: updateProfile
      tags: [Profile]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProfileUpdateRequest'
      responses:
        '200':
          description: Profile updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfile'
        '400':
          description: Validation error
        '401':
          description: Not authenticated
        '404':
          description: Profile not found

  /profile/personalization:
    get:
      summary: Get personalization rules for current user
      operationId: getPersonalizationRules
      tags: [Profile, Personalization]
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Personalization rules
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonalizationRules'
        '401':
          description: Not authenticated

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UserProfile:
      type: object
      properties:
        id:
          type: string
          format: uuid
        userId:
          type: string
          format: uuid
        codingLevel:
          type: string
          enum: [beginner, intermediate, advanced]
        hasNvidiaGpu:
          type: boolean
        hasRobot:
          type: boolean
        robotPlatform:
          type: string
          nullable: true
          enum: [unitree, boston_dynamics, custom, other, null]
        primaryInterest:
          type: string
          enum: [software, hardware, both]
        preferredLanguage:
          type: string
          enum: [en, ur]
        learningGoals:
          type: string
          nullable: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ProfileCreateRequest:
      type: object
      required:
        - codingLevel
      properties:
        codingLevel:
          type: string
          enum: [beginner, intermediate, advanced]
        hasNvidiaGpu:
          type: boolean
          default: false
        hasRobot:
          type: boolean
          default: false
        robotPlatform:
          type: string
          nullable: true
          enum: [unitree, boston_dynamics, custom, other]
        primaryInterest:
          type: string
          enum: [software, hardware, both]
          default: both
        preferredLanguage:
          type: string
          enum: [en, ur]
          default: en
        learningGoals:
          type: string
          maxLength: 1000

    ProfileUpdateRequest:
      type: object
      properties:
        codingLevel:
          type: string
          enum: [beginner, intermediate, advanced]
        hasNvidiaGpu:
          type: boolean
        hasRobot:
          type: boolean
        robotPlatform:
          type: string
          nullable: true
          enum: [unitree, boston_dynamics, custom, other]
        primaryInterest:
          type: string
          enum: [software, hardware, both]
        preferredLanguage:
          type: string
          enum: [en, ur]
        learningGoals:
          type: string
          maxLength: 1000

    PersonalizationRules:
      type: object
      properties:
        showBeginnerContent:
          type: boolean
          description: Show additional explanations for beginners
        showAdvancedContent:
          type: boolean
          description: Show advanced topics and optimizations
        showIsaacSimContent:
          type: boolean
          description: Show NVIDIA Isaac Sim specific content
        showGazeboContent:
          type: boolean
          description: Show Gazebo specific content
        showHardwareContent:
          type: boolean
          description: Show physical robot setup guides
        preferredLanguage:
          type: string
          enum: [en, ur]
        contentFilters:
          type: array
          items:
            type: object
            properties:
              selector:
                type: string
                description: CSS selector for content block
              action:
                type: string
                enum: [show, hide, highlight]
